import fsp from 'node:fs/promises'
import path from 'node:path'
import { describe, expect, test } from 'vitest'
import { splitTextToSentencesWithAI } from '../align'

const getWords = async () => {
	const currentDir = import.meta.dirname
	const p = path.join(currentDir, './test.json')
	const result = await fsp.readFile(p, 'utf-8')
	const data = JSON.parse(result)

	const words = data.transcription.map((item: any) => ({
		word: item.text,
		start: item.offsets.from / 1000,
		end: item.offsets.to / 1000,
	}))

	const text = words.reduce((acc: string, item: any) => {
		return acc + item.word
	}, '')

	return { words, text }
}

describe('text-to-sentence', () => {
	test('splitTextToSentencesWithAI', { timeout: 1000 * 60 * 10 }, async () => {
		const { text } = await getWords()
		const sentences = await splitTextToSentencesWithAI(text)
		expect(sentences).toMatchInlineSnapshot(`
			[
			  "China's embassy in Washington released a statement.",
			  "It urges the White House to, quote, immediately correct its wrongdoings, end quote,",
			  "warning that China's response if American tariffs stay in place will, quote, continue to the end.",
			  "Perspective now from former U.N. Ambassador John Bolton,",
			  "who served as national security advisor in the first Trump administration,",
			  "and Richard Quest, CNN business editor at large and anchor of Quest means business.",
			  "So, Ambassador Bolton, I know you're not an economist,",
			  "but just from a strategic perspective, do you think China is going to blink",
			  "and try to cut a deal with the White House?",
			  "It certainly doesn't look like it, but what Trump is doing is a huge opportunity for China worldwide.",
			  "These tariffs are a form of economic illiteracy.",
			  "Trump has no idea, really, what he's talking about.",
			  "He doesn't understand how tariffs works.",
			  "He has said as recently as a few days ago he views trade surpluses and deficits",
			  "as like a profit and loss statement, which they certainly are not.",
			  "So what he's doing has put us in a very vulnerable position,",
			  "and probably in the worst position possible to go after the real country problem",
			  "in the international trading system, which is China.",
			  "Instead of taking on the country that's stolen our intellectual property for decades,",
			  "among other things, by gathering our allies together,",
			  "all of whom also suffer from China's intellectual property theft,",
			  "and engaging in concerted action, we're at war with our largest trading partners",
			  "while we're about to go to war with China as well.",
			  "It simply makes no sense, and it's just sad and depressing",
			  "that more Republicans haven't stood up and said that.",
			  "This is illiteracy.",
			  "Richard, what does it look like for Americans if the price of everything imported from China",
			  "effectively doubles overnight?",
			  "How much of that gets passed on to consumers?",
			  "Well, the ambassador calls it economic illiteracy.",
			  "I've called it economic vandalism because if you have 104% tariffs,",
			  "what the effect of things is going to happen is two things.",
			  "Number one, things simply won't be imported.",
			  "It's too expensive. It's become unprofitable, uneconomic.",
			  "Things simply will not be imported.",
			  "Think about Christmas toys that just won't arrive.",
			  "But there are many things now that, as the Chinese have reminded the United States",
			  "in a commentary a couple of days ago, there are many things that the U.S. only gets from China.",
			  "Certain electronics, certain parts of manufacture, they can only now be received from China,",
			  "and the U.S. is going to find that they're going to be left without.",
			  "They're going to be trying to source it elsewhere.",
			  "And one point to remember, Anderson, tonight, oh yes, you've got the 104% against China,",
			  "but you've got the 24% against Japan.",
			  "And of course, there's the 25% autos.",
			  "You've got the 15% against South Korea, and you've got the 20% against the European Union.",
			  "So wherever you look at midnight tonight, the global trading network",
			  "is about to come under the most ferocious strain that it's seen,",
			  "certainly since the Second World War.",
			  "Ambassador Bolton, I mean, the first Trump administration,",
			  "you know, some talked about a so-called madman theory",
			  "that when it comes to national security, the idea that adversaries won't challenge the president",
			  "if they think he's unpredictable.",
			  "Does it make any sense to apply that same philosophy to allied trading partnerships?",
			  "No, look, the madman theory has a rationale behind it.",
			  "When Richard Nixon recommended it to Henry Kissinger dealing with China,",
			  "because Richard Nixon was well-known as an anti-communist,",
			  "he had made his political reputation on that.",
			  "So when he told Kissinger to basically say Nixon might use nuclear weapons",
			  "in the particular context they were talking about, use them against China,",
			  "it made sense because Nixon believed he was a hard-line anti-communist.",
			  "Trump doesn't believe in anything.",
			  "He's simply transactional, anecdotal, episodic,",
			  "and that's what these tariff policies have looked like in their rollout.",
			  "Richard, the New York Times described the market decline",
			  "as on par with the early days of the COVID-19 pandemic.",
			  "Does that signal that investors view this policy decision by the president",
			  "as equally volatile, as a deadly new disease with no known treatment or cure sweeping across the globe?",
			  "I think there's a similarity because in both cases, we didn't know how it was going to turn out.",
			  "The only difference being that in one particular case in COVID,",
			  "there was this massive effort towards sorting it out",
			  "and we had a vision of where he wanted to go.",
			  "And everybody seemed to be moving in the same direction",
			  "in this particular case because we don't know what the end game looks like.",
			  "We don't know.",
			  "You see, even if, just for argument's sake, let's say the tariffs all come down to zero.",
			  "Just humor me. They all come down to zero.",
			  "You've now got, you've still got the non-tariff barriers",
			  "which would prevent the U.S. from getting into new export markets.",
			  "And you've got the offensive behavior that the U.S. has put on its allies.",
			  "You know, Elizabeth Warren was talking about it a second ago",
			  "and the ambassador knows you can't just have a trade policy in isolation.",
			  "not when you've told Canada you regard them as the 51st state",
			  "and you've offended the EU talking about Denmark and Greenland.",
			  "Eventually, all these strands come together so that you don't have allies.",
			  "You have people wanting to do a deal.",
			  "That's pure, unadulterated self-interest.",
			  "But what you don't have is the commonality of view and value",
			  "that will get you over the line.",
			  "Ambassador, I mean, long-term, is it breaking of, you know, relationships",
			  "that have taken decades to form internationally?",
			  "Is there, I mean, is there a long-term cost on this, whatever the short-term impact is?",
			  "I think we've incurred a lot of the cost already,",
			  "not just because of Trump's tariff policy, but what he's done on Ukraine,",
			  "what he's done to NATO, what he threatens to do to NATO.",
			  "I can see all over the world, from Europe to the Far East,",
			  "that decades of effort by many, many Americans, in government and out of government,",
			  "to build up relationships of trust, of good faith, of reliance, of dependability,",
			  "that the United States deserves to be the leader of the world",
			  "to protect its own interests, not because of economic relations,",
			  "but because people trust us.",
			  "They don't trust us anymore, and it's going to be very hard to rebuild.",
			  "This is the wide open gap that we have left for the Chinese to drive through,",
			  "and I think they're moving along.",
			  "Trump simply doesn't grasp any of that.",
			  "He doesn't understand alliances as long-term propositions.",
			  "He just sees them as one transaction after the other,",
			  "and that's not the way they work.",
			  "Starting off tonight, Senator Elizabeth Warren, Democrat of Massachusetts,",
			  "who sits in the finance community and is the ranking member on the banking committee.",
			  "So with these tariffs about to go into effect in China overnight, around midnight,",
			  "how much more economic pain are we all facing?",
			  "Well, we're facing a lot of pain,",
			  "and understand, we look at the Dow Jones and the S&P because those are easy numbers to track,",
			  "but the reality is this is already being felt by families,",
			  "partly because prices are going up.",
			  "We already see the soft data showing us that there are a lot of companies out there saying,",
			  "you know what, we can tell what's coming, we're just going to raise our prices now,",
			  "and then if we need to raise them more later, we will do that.",
			  "The head of the Fed said on Friday that this kind of across-the-board tariffs",
			  "means prices will go up for families.",
			  "We'll see more inflation.",
			  "But he also pointed out unemployment is likely to go up as well.",
			  "So there are going to be people who lose their jobs.",
			  "We talk about this recession, Goldman Sachs, J.P. Morgan.",
			  "Do you think it's likely?",
			  "Oh, I think that all of the signs, the economic signs, are flashing red.",
			  "And remember, we lost 700,000 jobs a month in the last recession.",
			  "Recessions are not just things that happen on Wall Street.",
			  "They are things that happen family by family by family.",
			  "And there are people who never recover from that.",
			  "Do you also see long-term damage done to just the credibility, the confidence, the stability",
			  "of the United States?",
			  "Boy, you have put your finger on it.",
			  "Yes. Donald Trump is demonstrating that so long as he is president,",
			  "the United States is not a reliable trading partner,",
			  "but also not a reliable ally.",
			  "And domestically, think about what it means with these tariffs that are changing by the day.",
			  "People are saying they're on, they're off.",
			  "They're on, they're off, they're off, they're on, right?",
			  "Who makes investments here?",
			  "Who wants to say, I'm going to build a factory that will take me 20 years to recover my costs",
			  "without having some general sense of what it's going to be like",
			  "and the ability to sell your goods overseas.",
			  "You cannot plan. You cannot plan.",
			  "And in fact, what often happens is people start laying off hoarding their cash",
			  "under these circumstances.",
			  "That is the reason that it is now time for Congress to act.",
			  "we have the power in the Senate and the House to roll back the authority",
			  "that Donald Trump is using.",
			  "It's a simple resolution.",
			  "It will go to the floor.",
			  "Senator Ron Wyden and I have introduced it or will be introducing it the next day in the Senate.",
			  "You need how many Republicans?",
			  "Well, we only need a simple majority to get it passed.",
			  "We may need more than that if the president ultimately vetoes it.",
			  "But you know, this is the moment for Republicans.",
			  "This is the place where it's right in front of them.",
			  "Either they can continue to bend a knee to Donald Trump",
			  "or they can stand up for the people back home who are getting hurt by Donald Trump.",
			]
		`)
	})
})
